# Deploys smokeager codebase on server

- name : Deploy codebase on smokeager server
  hosts: "smokeager_server"
  user: aliasav
  become: aliasav
  become_user: aliasav
  gather_facts: true
  roles:
    - smokeager_deploy