# Deploys smokeager codebase on server

- name : Deploy codebase on smokeager server
  hosts: "smokeager_server"
  user: root
  sudo: yes
  sudo_user: aliasav
  gather_facts: false
  roles:
    - smokeager_deploy